name: llama-4-researcher

services:
  llama_redis:
    image: redis
    ports: 
      - 6380:6379
    networks:
      - nginxproxymanager_default
  llama_app:
    build:
      context: .
      dockerfile: Dockerfile
    secrets:
      - groq_key
      - internal_key
      - linkup_key
      - supabase_api_key
      - supabase_api_url
      - postgres_host
      - postgres_user
      - postgres_db
      - postgres_password
    networks:
      - nginxproxymanager_default 
    ports:
      - 7998:80
  llama_register:
    build:
      context: .
      dockerfile: Dockerfile.register
    secrets:
      - supabase_api_key
      - supabase_api_url
    networks:
      - nginxproxymanager_default 
    ports:
      - 7860:80
      
networks:
  nginxproxymanager_default:
    external: true

secrets:
  groq_key:
    environment: groq_api_key
  linkup_key:
    environment: linkup_api_key
  internal_key:
    environment: internal_api_key
  supabase_api_key:
    environment: supa_key
  supabase_api_url:
    environment: supa_url 
  postgres_host:
    environment: pgql_host
  postgres_user:
    environment: pgql_user
  postgres_password:
    environment: pgql_psw
  postgres_db:
    environment: pgql_db

volumes:
  pgdata: